Repository neovide/neovide, pull requests merged in 2025-01, with the labels that each got.

#2945 docs: macOS login shells
  website/docs/assets/login-shell.png
  website/docs/faq.md
Labels: documentation, macos

#2928 fix: execute login using zsh shell configuration
  src/bridge/command.rs
Labels: macos

#2971 add quake mode accessibility like terminals (with different spaces)
  website/docs/SUMMARY.md
  website/docs/editing-with-external-tools.md
  website/docs/integration-with-external-tools.md
Labels: macos

#2835 De-globalize RUNNING_TRACKER and SETTINGS
  src/bridge/command.rs
  src/bridge/handler.rs
  src/bridge/mod.rs
  src/bridge/setup.rs
  src/bridge/ui_commands.rs
  src/cmd_line.rs
  src/editor/cursor.rs
  src/editor/mod.rs
  src/error_handling.rs
  src/main.rs
  src/renderer/cursor_renderer/mod.rs
  src/renderer/d3d.rs
  src/renderer/grid_renderer.rs
  src/renderer/metal.rs
  src/renderer/mod.rs
  src/renderer/opengl.rs
  src/renderer/profiler.rs
  src/renderer/rendered_window.rs
  src/renderer/vsync/mod.rs
  src/renderer/vsync/vsync_timer.rs
  src/running_tracker.rs
  src/settings/mod.rs
  src/settings/window_size.rs
  src/window/error_window.rs
  src/window/keyboard_manager.rs
  src/window/macos.rs
  src/window/mod.rs
  src/window/mouse_manager.rs
  src/window/update_loop.rs
  src/window/window_wrapper.rs
Labels: hacktoberfest-accepted
